### ISSUE TITLE
Vertical smoothing not working

### ISSUE THREAD

**Issue by drollinger** [doonv/bevy_smooth_pixel_camera#1]
I'm making this issue in case anyone else has run into something similar. I'm on a mac and vertical movement was only snapping to the pixel grid. To fix this in the smooth_camera system I multiplied the remaindery by -1 instead of currently it is multiplied by 1. TBH not exactly sure why this works (probably just the way the orientation in bevy works). The sample code below works but I highly doubt it's the cleanest way to do this. I'm mostly just creating this issue in case someone else runs into this.

```
        let remainderx = (*subpixel_pos).x % 1.0;
        let remaindery = -1.0 * ((*subpixel_pos).y % 1.0);

        sprite.rect = Some(Rect {
            min: Vec2::new(remainderx + 1.0, remaindery + 1.0),
            max: image.size_f32() - Vec2::new(1.0 - remainderx, 1.0 - remaindery),
        })
```

**Comment by doonv** [comment]
I am able to reproduce the issue, and I'm able to fix it by inverting the Y axis. Will push a fix soon.
