### ISSUE TITLE
Add fitMode where the scaling is only integer.

### ISSUE THREAD

**Issue by wandbrandon** [doonv/bevy_smooth_pixel_camera#6]
Working with FitMode::Fit should have an option for only integer scaling, perhaps FitMode::FitInteger(i32)? 

Love this implementation, excited to see the panic bug fixed in 0.13!

**Comment by doonv** [comment]
I don't really understand what you mean. What is the integer for?

**Comment by wandbrandon** [comment]
with a fixed viewport, limiting the image to only scale using integer scaling. That way the pixel size is always consistent.

[Here is a write up I found online](https://tanalin.com/en/articles/integer-scaling/)

**Comment by doonv** [comment]
Ah, I see. I'll work on a solution.

**Comment by doonv** [comment]
@wandbrandon Is this the behavior you are looking for?

https://github.com/doonv/bevy_smooth_pixel_camera/assets/58695417/3f6031e6-3440-4316-8eef-270ab3a1f0cb

**Comment by wandbrandon** [comment]
Sorry for the late reply, yes exactly!
